version: "3"

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    container_name: "postgres_dev"
    restart: always
    volumes:
      - ./database_myscheduler:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  database_myscheduler: